name = "EPHS"
uuid = "a154ac86-a732-4cd8-94ce-a74caa38ec4b"
authors = ["Markus Lohmayer <markus.lohmayer@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
Reexport = "1.2.2"
RuntimeGeneratedFunctions = "0.5.13"
StaticArrays = "1.9.10"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
