name = "EPHS"
uuid = "a154ac86-a732-4cd8-94ce-a74caa38ec4b"
authors = ["Markus Lohmayer <markus.lohmayer@gmail.com>"]
version = "0.1.0"

[deps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrderedCollections = "bac558e1-5e72-5ebc-8fee-abe8a469f55d"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
RuntimeGeneratedFunctions = "7e49a35a-f44a-4d26-94aa-eba1b4ca6b47"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[weakdeps]
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
PlotsExt = "Plots"

[compat]
ForwardDiff = "0.10.38"
LinearAlgebra = "1.11.0"
OrderedCollections = "1.8.0"
Plots = "1.40.9"
Reexport = "1.2.2"
RuntimeGeneratedFunctions = "0.5.13"
StaticArrays = "1.9.10"
