[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
EPHS = "a154ac86-a732-4cd8-94ce-a74caa38ec4b"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
Documenter = "1.8"
